"""empty message

Revision ID: f4590a8cef1d
Revises: 
Create Date: 2023-04-15 11:37:57.711624

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f4590a8cef1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicators',
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('idx_indicator_name', 'indicators', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_indicator_name', table_name='indicators')
    op.drop_table('indicators')
    # ### end Alembic commands ###
