@startuml
!define primary_key(x) <b><color:#2688d4><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&key></color> x
!define column(x) <color:#efefef><&media-record></color> x
!define table(x) entity x << (T, #f2f2f2) >>
left to right direction
skinparam {
    ArrowColor #2688d4
    BorderColor #2688d4
    BackgroundColor #ffffff
    roundcorner 10
    handwritten false
    class {
        BackgroundColor #f2f2f2
        BorderColor #2688d4
        ArrowColor #2688d4
        FontColor #333333
    }
}
table(symbol) {
    primary_key(id): int
    primary_key(name): varchar(9)
    column(base_asset): varchar(5)
    column(quote_asset): varchar(5)
    column(created_at): timestamp
    column((updated_at):timestamp
}

table(futures_symbols) {
    primary_key(id): uuid
    column(name): varchar
    column(isActive): bool
    foreign_key(symbol_id): int <<FK>>
    column(created_at): timestamp
    column(updated_at): timestamp
}

table(futures_assets){
    primary_key(id): id
    primary_key(name): varchar
    column(quantity): int
    column(created_at): timestamp
    column(updated_at): timestamp
}
table(indicators){
    primary_key(id): int
    primary_key(name): varchar
    column(created_at): timestamp
    column(updated_at): timestamp
}

table(futures_indicators){
    primary_key(id): int
    foreign_key(indicator_id): int <<FK>>
    column(isActive): bool
    column(created_at): timestamp
    column(updated_at): timestamp
}

table(binance_errors){
    primary_key(id): uuid
    column(code): int
    column(description): text
    column(created_at): timestamp
}

futures_symbols |o-- symbol
futures_indicators |o-- indicators

@enduml

'Type	Symbol
'Zero or One	|o--
'Exactly One	||--
'Zero or Many	}o--
'One or Many	}|--

'https://plantuml.com/ie-diagram